plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'com.denysov'
version = '1.0.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = '21.0.5'
    modules = ['javafx.controls', 'javafx.media']
}

application {
    mainClass = 'com.denysov.calculator.CalculatorApplication'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

tasks.register('prepareJpackageInput', Sync) {
    dependsOn tasks.named('jar')
    from(tasks.named('jar').flatMap { it.archiveFile })
    from(configurations.runtimeClasspath)
    into(layout.buildDirectory.dir('jpackage-input'))
}
